name: doxygen build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Doxygen setup
        run: |
          sudo apt-get install -y doxygen graphviz
          
      - name: Clean Old Documentation Builds
        run: |
          rm -rf doc/generated

      - name: Generate Doxygen
        run: |
          doxygen --version
          doxygen Doxyfile

      - name: Upload Documentation Artifact
        # This step uploads the HTML files for deployment, but only on the main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v5
        with:
          path: doc/generated/html

  deploy-docs:
    # Only run this job on a push to the main branch, after the build job succeeds
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: doxygen-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v5

