name: doxygen build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Doxygen setup
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen
        run: |
          doxygen Doxyfile

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: doc/generated/html
